name: 'Generate docs'
description: 'Generate docs for NEAR'
branding:
  icon: book-open
  color: green
inputs:
  docs_source:
    description: 'Source repo to generate docs for'
    required: true
  release_version:
    description: 'Release version'
    required: true
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
runs:
  using: node16
  main: 'build-ncc/index.js'