name: 'Generate docs'
description: 'Generate docs for NEAR'
branding:
  icon: book-open
  color: green
inputs:
  docs_source:
    description: 'Source repo to generate docs for'
    required: true
  release_version:
    description: 'Release version'
    required: true
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
runs:
  using: 'composite'
  steps:
  - uses: actions/setup-node@v3
    with:
      node-version: 16
  - run: |
      which git
      ls -la
      sudo apt-get -y install git
      git pull https://github.com/maxhr/near--docs-generator ./generator
      cd generator
      node build-ncc/index.js
    shell: bash