name: Publish docs

on:
  repository_dispatch:
    types: [publish-naj,publish-cli,publish-js-sdk,publish-rust-sdk]

concurrency:
  group: ${{ github.event.type }}
  cancel-in-progress: true

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          yarn install
      - name: Publish
        run: |
          yarn publish-github ${{ github.event }}
